### ISSUE TITLE
Missing texture for all items

### ISSUE THREAD

**Issue by Volondil** [2xsaiko/rswires#22] opened 2021-09-15 10:23 UTC
All textures are unable to load. I'm running it with fabric 0.11.6 and fabric api 0.40.1

Here is what i found through the log file:

[https://mega.nz/file/zw9GmTyY#ubDWprTtZCVCRfyHo25qkueZ5bC6ErHlzH9UF4g1Y8Q](url)

**Comment by dblsaiko** [comment] 2021-09-15 10:57
Duplicate of #18, there's no Fabric Renderer API available because of another mod, probably Sodium. If you're using Sodium, install Indium additionally.

**Closed as completed by dblsaiko** 2021-09-15 10:57 UTC
Labels: duplicate, wontfix, notabug
